### PR TITLE
Task 3

### PR DESCRIPTION
**Pull request by jelenanemcic**

### CODE REVIEW

**Comment by vpintaric-axilis** [comment]
It seems that this PR includes both task2 and task3 implementation. Could you remove task2 implementation from this PR?

**Comment by jelenanemcic** [comment]
> It seems that this PR includes both task2 and task3 implementation. Could you remove task2 implementation from this PR?

I am afraid that I do not know how to do that. I thought that when I merge task2 it would disappear from this PR? So maybe I could merge it before the review of task3.

**Comment by vpintaric-axilis** [comment]
> I am afraid that I do not know how to do that.

Easiest way to do that considering that tasks are completely separated in different folders:
* Copy the whole folder of task3 somewhere outside of this git repository, that would be the `event_settler` folder I believe
* Checkout to the main branch, `git checkout main`
* Create a new branch, e.g. `git checkout -b task3`
* Copy the task3 folder back into the repository
* Commit everything, `git add -A` -> `git commit -m "3rd task implementation"` -> `git push -u origin task3`
* Close this PR and open a new one with the newly pushed branch OR simply change the source branch in this PR

There are other ways to do this, by cherry picking commits and force pushing the branch but that's not so easy to explain via a comment here.

> I thought that when I merge task2 it would disappear from this PR? So maybe I could merge it before the review of task3.

The thing is there are commits from task1 and task2 on this branch and then there's task3 implementation. What do you think happens when you update task1 and task2 PRs and then merge those? You're gonna get merge conflicts here. In this case it would be relatively easy to fix but you should never depend on some other PR being merged in your PR. Only assume that the code currently on the `main` branch is stable and only thing you can depend on.

**Comment by jelenanemcic** [comment]
> * Close this PR and open a new one with the newly pushed branch OR simply change the source branch in this PR

Done! New PR is here: https://github.com/jelenanemcic/code-cadets-2021/pull/18

I will close this one once you have seen the comment.

**Comment by vpintaric-axilis** [comment]
> I will close this one once you have seen the comment.

Closing a PR doesn't delete it or any comments within it so no worries about that.

**Pull request closed without merging**
